<?php

include_once('inc_base.features.inc');

function inc_base_system_info_alter(&$info, $file) {
  if ($info['name'] == "Features Tests") {
    global $user;
    if ($user->uid !== 1) unset ($info['features']);
  }
}


function inc_base_form_alter(&$form, &$form_state, $form_id) {
  // NODE FORMS --------------------------------------------
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id) {
    if (isset($form['field_main_image']) && $form['field_main_image']['#weight'] < 0) {
      drupal_add_css(drupal_get_path('module', 'inc_base') . '/css/inc_base_node_forms.css');
      foreach (array('body_field', 'field_event_date', 'field_event_info') as $key) {
        if (isset($form[$key])) {
          $form[$key]['#prefix'] = '<div class="node-form-float-left">' . $form[$key]['#prefix'];
          $form[$key]['#suffix'] .= '</div>';
        }
      }
      $form['field_main_image']['#description'] = t('<ul><li>640px minimum for good display</li>
        <li>Will display on page, teaser and rss feeds</li></ul>');
    }
    if (isset($form['taxonomy'])) {
      if (!variable_get('inc_glue_activity_vid', 0)) { 
        $form['taxonomy']['#type'] = 'fieldset';
        $form['taxonomy']['#title'] = t('Tags and Categories');
      }
    }
  }
  // USER PROFILE FORM
  elseif ($form_id == 'user_profile_form') {
    if (user_access('administer permissions')) {
      foreach(array('profile_firstname', 'profile_lastname') as $key) {
        if (isset($form['Bio'][$key])) {
          $form['Bio'][$key]['required'] = FALSE;
        }
      }
    }
  }
  // ADMIN FORMS
  if (arg(0) == 'admin') {

    // add styles for admin forms (which use seven theme by default)
    drupal_add_css(drupal_get_path('module', 'inc_base') . '/css/inc_base_admin_forms_mods.css');

    // make the theme's custom settings appear at the top of Skinr's long form
    if (isset($form['skinr_settings'])) {
      $form['skinr_settings']['#weight'] = 1;
      foreach (element_children($form['skinr_settings']) as $feature) {
        $form['skinr_settings'][$feature]['#group'] = 'skinr_' . $feature;
        foreach (element_children($form['skinr_settings'][$feature]) as $theme) {
          foreach (element_children($form['skinr_settings'][$feature][$theme]['widgets']) as $field) {
            if (stripos($field, $theme) !== FALSE) {
              $form['skinr_settings'][$feature][$theme]['widgets'][$field]['#weight'] = -100;
            }
          }
        }
      }
    }

  }

}
